In [1]:
# example of using the transpose convolutional layer

from numpy import asarray
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2DTranspose

In [2]:
# define the data

X = asarray([[1,2],
             [3,4]])
print(X)

[[1 2]
 [3 4]]


In [3]:
# reshape input data
X = X.reshape((1,2,2,1))
print(X)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [4]:
# define model

model = Sequential()

model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2,2,1)))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose (Conv2DTra  (None, 4, 4, 1)          2         
 nspose)                                                         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [5]:
weights = [asarray([[[[1]]]]), asarray([0])]

model.set_weights(weights)

In [6]:
yhat = model.predict(X)
yhat = yhat.reshape((4,4))
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


In [7]:
model2 = Sequential()
model2.add(Conv2DTranspose(filters=1, kernel_size=(1,1), strides=(3,3), input_shape=(2,2,1)))

model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose_1 (Conv2DT  (None, 6, 6, 1)          2         
 ranspose)                                                       
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
model2.set_weights(weights=weights)

yhat = model2.predict(X)
yhat = yhat.reshape((6,6))
print(yhat)

[[1. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Generative model
---

In [9]:
# example of using transpose conv in a simple generator model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape, Conv2DTranspose

# define the model

model = Sequential()

model.add(Dense(128*5*5, input_dim=100))
model.add(Reshape((5,5,128)))
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3200)              323200    
                                                                 
 reshape (Reshape)           (None, 5, 5, 128)         0         
                                                                 
 conv2d_transpose_2 (Conv2DT  (None, 10, 10, 1)        1153      
 ranspose)                                                       
                                                                 
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
