In [12]:
# example of using the upsampling layer

from numpy import asarray
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import UpSampling2D, Input

In [2]:
# define input data
X = asarray([[1,2],
             [3,4]])

# show input data for context
#print(X)
X

array([[1, 2],
       [3, 4]])

In [3]:
# reshape input data into a sample with one channel
X = X.reshape((1,2,2,1))
#print(X)
X

array([[[[1],
         [2]],

        [[3],
         [4]]]])

In [4]:
# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))

In [5]:
# summarize model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 up_sampling2d (UpSampling2D  (None, 4, 4, 1)          0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [6]:
# make a prediction with the model
yhat = model.predict(X)
#print(yhat)
yhat

array([[[[1.],
         [1.],
         [2.],
         [2.]],

        [[1.],
         [1.],
         [2.],
         [2.]],

        [[3.],
         [3.],
         [4.],
         [4.]],

        [[3.],
         [3.],
         [4.],
         [4.]]]], dtype=float32)

In [7]:
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4,4))

In [8]:
# summarize output
#print(yhat)
yhat

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [3., 3., 4., 4.],
       [3., 3., 4., 4.]], dtype=float32)

In [9]:
model2 = Sequential()
model2.add(UpSampling2D(input_shape=(2,2,1), size=(3,3)))
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 up_sampling2d_1 (UpSampling  (None, 6, 6, 1)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [10]:
yhat = model2.predict(X)
yhat = yhat.reshape((6,6))
print(yhat)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


In [13]:
visible = Input(shape=(2,2,1))
outputs = UpSampling2D(input_shape=(2,2,1),
                       size=(4,4),
                       interpolation='bilinear')(visible)
model3 = Model(inputs=visible, outputs=outputs)
model3.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 2, 2, 1)]         0         
                                                                 
 up_sampling2d_2 (UpSampling  (None, 8, 8, 1)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [14]:
yhat = model3.predict(X)
yhat = yhat.reshape((8,8))
print(yhat)

[[1.    1.    1.125 1.375 1.625 1.875 2.    2.   ]
 [1.    1.    1.125 1.375 1.625 1.875 2.    2.   ]
 [1.25  1.25  1.375 1.625 1.875 2.125 2.25  2.25 ]
 [1.75  1.75  1.875 2.125 2.375 2.625 2.75  2.75 ]
 [2.25  2.25  2.375 2.625 2.875 3.125 3.25  3.25 ]
 [2.75  2.75  2.875 3.125 3.375 3.625 3.75  3.75 ]
 [3.    3.    3.125 3.375 3.625 3.875 4.    4.   ]
 [3.    3.    3.125 3.375 3.625 3.875 4.    4.   ]]


---
Generative model
---

In [15]:
# example of using upsampling in a simple generator model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Reshape, UpSampling2D

In [16]:
# define the model
model = Sequential()

model.add(Dense(128*5*5, input_dim=100))
model.add(Reshape((5,5,128)))
model.add(UpSampling2D())
model.add(Conv2D(1, (3,3), padding='same'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3200)              323200    
                                                                 
 reshape (Reshape)           (None, 5, 5, 128)         0         
                                                                 
 up_sampling2d_3 (UpSampling  (None, 10, 10, 128)      0         
 2D)                                                             
                                                                 
 conv2d (Conv2D)             (None, 10, 10, 1)         1153      
                                                                 
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
