In [2]:
import tensorflow as tf

In [3]:
from tensorflow import keras

In [5]:
tf.constant([[1.,2.,3.],[4.,5.,6.]])

2022-01-27 21:53:43.751768: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-27 21:53:43.752336: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
tf.constant(42)

<tf.Tensor: id=1, shape=(), dtype=int32, numpy=42>

In [7]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t.shape

TensorShape([2, 3])

In [8]:
t.dtype

tf.float32

In [9]:
t[:, 1:]

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [10]:
t[...,1,tf.newaxis]

<tf.Tensor: id=10, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [11]:
t

<tf.Tensor: id=2, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [12]:
t + 10

<tf.Tensor: id=12, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [13]:
tf.square(t)

<tf.Tensor: id=13, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [14]:
t @ tf.transpose(t)

<tf.Tensor: id=16, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [15]:
t1 = tf.constant([1,2])

In [16]:
t2 = tf.constant([[1],[2]])

In [17]:
t1, t2

(<tf.Tensor: id=17, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: id=18, shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>)

In [19]:
t3 = tf.transpose(t1)

In [20]:
t1, t3

(<tf.Tensor: id=17, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: id=20, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [21]:
t

<tf.Tensor: id=2, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [22]:
tf.transpose(t)

<tf.Tensor: id=22, shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [23]:
t4 = tf.constant([[1,2,3,4]])

In [24]:
t4

<tf.Tensor: id=23, shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [25]:
tf.transpose(t4)

<tf.Tensor: id=25, shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [26]:
t4@tf.transpose(t4)

<tf.Tensor: id=28, shape=(1, 1), dtype=int32, numpy=array([[30]], dtype=int32)>

In [27]:
tf.square(t4)

<tf.Tensor: id=29, shape=(1, 4), dtype=int32, numpy=array([[ 1,  4,  9, 16]], dtype=int32)>

In [28]:
K = keras.backend

In [29]:
K.square(K.transpose(t4)) + 10

<tf.Tensor: id=34, shape=(4, 1), dtype=int32, numpy=
array([[11],
       [14],
       [19],
       [26]], dtype=int32)>

In [30]:
import numpy as np

In [31]:
a = np.array([2.,4.,5.])

In [32]:
tf.constant(a)

<tf.Tensor: id=35, shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [33]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [34]:
np.array(t4)

array([[1, 2, 3, 4]], dtype=int32)

In [35]:
tf.square(a)

<tf.Tensor: id=37, shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [37]:
np.square(t4)

array([[ 1,  4,  9, 16]], dtype=int32)

In [39]:
t5 = tf.constant(40., dtype=tf.float64)

In [40]:
tf.constant(2.0) + tf.cast(t5, tf.float32)

<tf.Tensor: id=43, shape=(), dtype=float32, numpy=42.0>

In [41]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])

In [42]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [43]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [44]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [45]:
v[0,1]

<tf.Tensor: id=62, shape=(), dtype=float32, numpy=4.0>

In [46]:
v[0,1].assign(43)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 43.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [47]:
v[:,2].assign([0.,1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 43.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [50]:
v[:,2].assign([9,9])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 43.,  9.],
       [ 8., 10.,  9.]], dtype=float32)>

In [51]:
v.scatter_nd_update(indices=[[0,0],[1,2]],updates=[100.,200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  43.,   9.],
       [  8.,  10., 200.]], dtype=float32)>

In [53]:
a = 0
for _ in range(1+3):
    a+=_
    print(a)

0
1
3
6


In [54]:
def f(w1,w2):
    return 3 * w1 ** 2 + 2 * w1 * w2

In [55]:
w1, w2 = 5, 3

In [56]:
eps = 1e-6

In [58]:
(f(w1 + eps, w2) - f(w1,w2))/eps

36.000003007075065

In [59]:
(f(w1, w2+eps) - f(w1,w2))/eps

10.000000003174137

In [65]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1,w2)
    
gradients = tape.gradient(z, [w1,w2])

In [66]:
gradients

[<tf.Tensor: id=136, shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: id=128, shape=(), dtype=float32, numpy=10.0>]

In [69]:
with tf.GradientTape() as tape:
    z = f(w1,w2)
    
dz_w1 = tape.gradient(z, w1)
dz_w1

<tf.Tensor: id=208, shape=(), dtype=float32, numpy=36.0>

In [70]:
with tf.GradientTape(persistent=True) as tape:
    z = f(w1,w2)
    
dz_w1 = tape.gradient(z, w1)
dz_w2 = tape.gradient(z, w2)
del tape

In [71]:
dz_w1, dz_w2

(<tf.Tensor: id=232, shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: id=237, shape=(), dtype=float32, numpy=10.0>)

In [72]:
c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
    z = f(c1,c2)
    
gradients = tape.gradient(z, [c1,c2])
gradients

[None, None]

In [74]:
with tf.GradientTape() as tape:
    tape.watch(c1)
    tape.watch(c2)
    z = f(c1,c2)
    
gradients = tape.gradient(z, [c1,c2])
gradients

[<tf.Tensor: id=296, shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: id=288, shape=(), dtype=float32, numpy=10.0>]

In [77]:
def f(w1,w2):
    return 3*w1**2 + tf.stop_gradient(2*w1*w2)

with tf.GradientTape() as tape:
    z = f(w1,w2)
    
gradients = tape.gradient(z, [w1,w2])
gradients

[<tf.Tensor: id=336, shape=(), dtype=float32, numpy=30.0>, None]

In [80]:
l2_reg = keras.regularizers.l2(0.05)
model = keras.models.Sequential([keras.layers.Dense(30, activation='elu', 
                                                    kernel_initializer='he_normal',
                                                    kernel_regularizer=l2_reg),
                                 keras.layers.Dense(1, kernel_regularizer=l2_reg)])

In [81]:
def random_batch(X,y,batch_size=32):
    idx = np.random.randint(len(X),size=batch_size)
    return X[idx], y[idx]

In [82]:
def print_status_bar(iteration, total, loss, metrics=True):
    metrics = ' - '.join(['{}: {:.4f}'.format(m.name, m.result())
                          for m in [loss] + (metrics or [])])
    end = '' if iteration < total else '\n'
    print('\r{}/{} - '.format(iteration, total) + metrics, end=end)

In [83]:
def cube(x):
    return x**3

In [84]:
cube(2)

8

In [85]:
cube(tf.constant(2.0))

<tf.Tensor: id=346, shape=(), dtype=float32, numpy=8.0>

In [86]:
tf_cube = tf.function(cube)
tf_cube

In [87]:
tf_cube(2)

<tf.Tensor: id=352, shape=(), dtype=int32, numpy=8>

In [88]:
tf_cube(tf.constant(2.0))

<tf.Tensor: id=360, shape=(), dtype=float32, numpy=8.0>

In [89]:
@tf.function
def tf_cube(x):
    return x**4

In [90]:
tf_cube.python_function(4)

256

In [91]:
tf_cube(2)

<tf.Tensor: id=366, shape=(), dtype=int32, numpy=16>

In [92]:
tf_cube(tf.constant(2.0))

<tf.Tensor: id=374, shape=(), dtype=float32, numpy=16.0>

In [93]:
tf_cube(2.0)

<tf.Tensor: id=375, shape=(), dtype=int32, numpy=16>